#!/bin/sh
# Builds OneTouch.app (universal: Apple Silicon + Intel) and OneTouch-mac.zip.
# Needs Xcode command line tools and Go. Run on macOS: sh macos/build.sh
set -eu
cd "$(dirname "$0")"
OUT=build
APP=$OUT/OneTouch.app
rm -rf "$OUT"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

for arch in arm64 x86_64; do
  swiftc -O -target "$arch-apple-macos13.0" -framework AppKit -framework UserNotifications -framework ServiceManagement \
    Sources/*.swift -o "$OUT/OneTouch-$arch"
done
lipo -create "$OUT/OneTouch-arm64" "$OUT/OneTouch-x86_64" -output "$APP/Contents/MacOS/OneTouch"

( cd ../core
  CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -trimpath -ldflags "-s -w" -o "../macos/$OUT/core-arm64" ./cmd/onetouch
  CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -trimpath -ldflags "-s -w" -o "../macos/$OUT/core-amd64" ./cmd/onetouch )
lipo -create "$OUT/core-arm64" "$OUT/core-amd64" -output "$APP/Contents/MacOS/onetouch-core"

cp Info.plist "$APP/Contents/Info.plist"

# App icon from an SF Symbol-like glyph drawn with sips-friendly PNG (generated by icon.swift).
swiftc -O icon.swift -o "$OUT/mkicon" -framework AppKit
"$OUT/mkicon" "$OUT/icon_1024.png"
ICONSET=$OUT/AppIcon.iconset
mkdir -p "$ICONSET"
for s in 16 32 128 256 512; do
  sips -z $s $s "$OUT/icon_1024.png" --out "$ICONSET/icon_${s}x${s}.png" >/dev/null
  d=$((s * 2))
  sips -z $d $d "$OUT/icon_1024.png" --out "$ICONSET/icon_${s}x${s}@2x.png" >/dev/null
done
iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/AppIcon.icns"

# Ad-hoc signature (no Apple Developer ID): required for Apple Silicon.
codesign --force --sign - "$APP/Contents/MacOS/onetouch-core"
codesign --force --sign - "$APP"
codesign --verify --verbose "$APP"

ditto -c -k --keepParent "$APP" "$OUT/OneTouch-mac.zip"
echo "✓ $OUT/OneTouch-mac.zip"
